Add support for Launchpad X
dszakallas/mixxx-launchpad pull request #94
Opened 2024-12-07 11:26 UTC by msprengholz

This branch adds initial support for the Launchpad X. It is based on the Launchpad Mini MK3 code. The only thing changed to get the Launchpad X working is changing the SysEx message to get the Launchpad X into programmer mode.

2024-12-18 21:59 UTC, dszakallas commented
Thanks for your PR @msprengholz! I will take a look on it on the weekend. Could you enable CI on your fork?

2025-01-03 11:59 UTC, msprengholz commented
Hi, I just got around to enable CI on my fork. I hope this helps. Let me know if I need to change something.

2025-01-29 20:42 UTC, dszakallas approved these changes
Thanks. It all looks good to me, thanks for your contribution.

2025-01-29 20:47 UTC, dszakallas requested changes
One more thing, please add to the list of devices in the README.md, including the notice about programmer mode.

2025-02-28 18:19 UTC, merged